### ISSUE TITLE
Set up django project

### ISSUE THREAD

**Issue by Vasileios20** [violaberg/memo-bubble-api#1]
### Tasks:

- [x] Install django-rest framework and required libraries
- [x] Set up JWT Web Token
- [x] Set up REST Framework render and pagination
- [x] Set up Cloudinary
- [x] Create Logout view ([issue with dj-rest-auth/logout](https://github.com/iMerica/dj-rest-auth/issues/246))
- [x] Set up CLIENT_ORIGIN
- [x] Set up for deployment

**Comment by Vasileios20** [comment]
Bug: \When click on link in the email confirmation return error : TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'

Fix: Create custom view to redirect to custom template's link (Update link with the one will be created on FE repo)

````class CustomConfirmEmailView(APIView, ConfirmEmailView):
    def get(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.confirm(self.request)
        return redirect("http://localhost:3000/email-confirmed/")
````
