### ISSUE TITLE
Add capsules app

### ISSUE THREAD

**Issue by Vasileios20** [violaberg/memo-bubble-api#4]
### Tasks:

- [x] Create models for capsule, images, videos and gemini messages
- [x] Create serializers
- - [x] Capsule model 
- - [x] Images model 
- - [x] Videos model 
- - [x] GeminiMessages model 
- - [x]  Implement create function
- - [x] Implement update function
- [x] Create views to handle CRUD functionality
 - - [x]  Implement create View
 - - [x] Implement update View
 - - [x] Implement delete Views
 - - - [x] Implement delete View for images
 - - - [x] Implement delete View for videos
 - - - [x] Implement delete View for gemini messages
- [x] Add urls endpoints
- - [x] Create View
- - [x] Update View
- - [x] Delete Image View
- - [x] Delete Video View
- - [x] Delete GeminiMessages View
